### PR TITLE
go-controller: fix typo in test script

### LINKED ISSUE #4942: Typo in referenced variable ginkgo_focus test-go.sh
In the [`test-go.sh` file in line 51](https://github.com/ovn-kubernetes/ovn-kubernetes/blob/326f9db796f3c44e7cdb0fa00ebe0c9c5b5a1a15/go-controller/hack/test-go.sh#L51) the variable `ginkgo_focus` is misspelled as `gingko_focus`.

As the latter var is not used anywhere else in this repo and is used to concatenate the var `ginkgo_focus` in the next line to `ginkgoargs` it seems to be a typo.

### PR DESCRIPTION
**Pull request by FSchumacher**
## 📑 Description

The variable ginkgo_focus is misspelled as gingko_focus.

As the latter var is not used anywhere else in this repo and is used to concatenate the var ginkgo_focus in the next line to ginkgoargs it seems to be a typo.

Fixes #4942

### CODE REVIEW

File: go-controller/hack/test-go.sh [hunk 1]
```diff
@@ -48,7 +48,7 @@ function testrun {
             go_test="sudo ${testfile}"
         fi
     fi
-    if [[ -n "$gingko_focus" ]]; then
+    if [[ -n "$ginkgo_focus" ]]; then
```
Comment (flavio-fernandes) [inline go-controller/hack/test-go.sh:51]: nice catch. Thanks!

**Review by flavio-fernandes — APPROVED** [review]

**Review by tssurya — APPROVED** [review]
thanks for the fix!
