### PR TITLE
Shared gateway: Modification of ClusterIPs shall trigger svc update

### LINKED ISSUE #2700: When converting a service from single stack to dual stack, IPv6 DNAT rules are not created
When converting a service from single stack to dual stack, IPv6 DNAT rules are not created (likely any other required logic isn't executed, either, to be verified).

As reported in https://bugzilla.redhat.com/show_bug.cgi?id=2028812

~~~
[root@ovnkubernetes ~]# ./kind.sh --ipv6 --ha-enabled
[root@ovnkubernetes ~]# export KUBECONFIG=~/admin.conf 
[root@ovnkubernetes ~]# oc apply -f netshoot.yaml 
service/netshoot-service created
deployment.apps/netshoot-deployment created
[root@ovnkubernetes ~]# oc get pods -o wide
NAME                                   READY   STATUS              RESTARTS   AGE   IP       NODE         NOMINATED NODE   READINESS GATES
netshoot-deployment-5b5567c8bc-5h6rm   0/1     ContainerCreating   0          4s    <none>   ovn-worker   <none>           <none>
[root@ovnkubernetes ~]# oc get pods -o wide --watch
NAME                                   READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
netshoot-deployment-5b5567c8bc-5h6rm   1/1     Running   0          36s   10.244.0.4   ovn-worker   <none>           <none>
^C[root@ovnkubernetes ~]# oc get svc
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
kubernetes         ClusterIP   10.96.0.1       <none>        443/TCP           4m54s
netshoot-service   NodePort    10.96.226.193   <none>        27017:30000/TCP   40s
[root@ovnkubernetes ~]# docker exec -it ovn-worker iptables-save | grep NODE
:OVN-KUBE-NODEPORT - [0:0]
-A PREROUTING -j OVN-KUBE-NODEPORT
-A OUTPUT -j OVN-KUBE-NODEPORT
-A OVN-KUBE-NODEPORT -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 30000 -j DNAT --to-destination 10.96.226.193:27017
[root@ovnkubernetes ~]# docker exec -it ovn-worker ip6tables-save | grep NODE
:OVN-KUBE-NODEPORT - [0:0]
-A PREROUTING -j OVN-KUBE-NODEPORT
-A OUTPUT -j OVN-KUBE-NODEPORT
[root@ovnkubernetes ~]# oc edit netshoot-service
error: the server doesn't have a resource type "netshoot-service"
[root@ovnkubernetes ~]# oc edit svc netshoot-service
service/netshoot-service edited
[root@ovnkubernetes ~]# oc get -o yaml svc netshoot-service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"netshoot-service","namespace":"default"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ports":[{"name":"http","nodePort":30000,"port":27017,"targetPort":8080}],"selector":{"app":"netshoot-pod"},"type":"NodePort"}}
  creationTimestamp: "2021-12-09T11:16:56Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":27017,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-12-09T11:16:56Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ipFamilies: {}
        f:ipFamilyPolicy: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-12-09T11:18:14Z"
  name: netshoot-service
  namespace: default
  resourceVersion: "1387"
  uid: 400f22a3-71da-4fc6-8c75-2937e86d69f3
spec:
  clusterIP: 10.96.226.193
  clusterIPs:
  - 10.96.226.193
  - fd00:10:96::713
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: http
    nodePort: 30000
    port: 27017
    protocol: TCP
    targetPort: 8080
  selector:
    app: netshoot-pod
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
[root@ovnkubernetes ~]# docker exec -it ovn-worker ip6tables-save | grep NODE
:OVN-KUBE-NODEPORT - [0:0]
-A PREROUTING -j OVN-KUBE-NODEPORT
-A OUTPUT -j OVN-KUBE-NODEPORT
[root@ovnkubernetes ~]# docker exec -it ovn-worker iptables-save | grep NODE
:OVN-KUBE-NODEPORT - [0:0]
-A PREROUTING -j OVN-KUBE-NODEPORT
-A OUTPUT -j OVN-KUBE-NODEPORT
-A OVN-KUBE-NODEPORT -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 30000 -j DNAT --to-destination 10.96.226.193:27017
[root@ovnkubernetes ~]# 
~~~

### PR DESCRIPTION
**Pull request by andreaskaris**
When switching a service from SingleStack to DualStack, its
ClusterIPs are updated. This change to ClusterIPs will now be detected
and ovnkube will write IPv6 DNAT rules to the host.

Fixes #2700

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by andreaskaris** [comment]
@npinaeva 
@trozet

File: go-controller/pkg/node/gateway_shared_intf.go [hunk 1]
```diff
@@ -503,10 +503,11 @@ func delServiceRules(service *kapi.Service, npw *nodePortWatcher) {
 	delGatewayIptRules(service, false)
 }
 
-func serviceUpdateNeeded(old, new *kapi.Service) bool {
+func serviceUpdateNotNeeded(old, new *kapi.Service) bool {
 	return reflect.DeepEqual(new.Spec.Ports, old.Spec.Ports) &&
 		reflect.DeepEqual(new.Spec.ExternalIPs, old.Spec.ExternalIPs) &&
 		reflect.DeepEqual(new.Spec.ClusterIP, old.Spec.ClusterIP) &&
+		reflect.DeepEqual(new.Spec.ClusterIPs, old.Spec.ClusterIPs) &&
```
Comment (msherif1234) [inline go-controller/pkg/node/gateway_shared_intf.go:510]: why this list doesn't include `*.Spec.LoadBalancerIP `

File: go-controller/pkg/node/gateway_shared_intf.go [hunk 2]
```diff
@@ -503,10 +503,11 @@ func delServiceRules(service *kapi.Service, npw *nodePortWatcher) {
 	delGatewayIptRules(service, false)
 }
 
-func serviceUpdateNeeded(old, new *kapi.Service) bool {
+func serviceUpdateNotNeeded(old, new *kapi.Service) bool {
 	return reflect.DeepEqual(new.Spec.Ports, old.Spec.Ports) &&
 		reflect.DeepEqual(new.Spec.ExternalIPs, old.Spec.ExternalIPs) &&
 		reflect.DeepEqual(new.Spec.ClusterIP, old.Spec.ClusterIP) &&
```
Comment (msherif1234) [inline go-controller/pkg/node/gateway_shared_intf.go:509]: shouldn't ClusterIPs will always be populated even with single IP, do we still need ClusterIP ?

File: go-controller/pkg/node/gateway_shared_intf.go (hunk 1 above)
Comment (msherif1234) [reply go-controller/pkg/node/gateway_shared_intf.go:510]: scratch that this field will be going away soon https://github.com/kubernetes/kubernetes/pull/107235

**Review by trozet — APPROVED** [review]
