### PR TITLE
Lock the cdr global variable

### LINKED ISSUE #3154: Race in unit test: Egress Service Operations
```
2022-09-09T14:39:13.8316190Z [32m•[0m
2022-09-09T14:39:13.8316803Z JUnit path was configured: /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/_artifacts/junit-pkg_ovn.xml
2022-09-09T14:39:13.8365251Z 
2022-09-09T14:39:13.8365824Z JUnit report was created: /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/_artifacts/junit-pkg_ovn.xml
2022-09-09T14:39:13.8366822Z 
2022-09-09T14:39:13.8367432Z [1m[32mRan 187 of 187 Specs in 372.627 seconds[0m
2022-09-09T14:39:13.8368723Z [1m[32mSUCCESS![0m -- [32m[1m187 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m
2022-09-09T14:39:13.8369519Z     testing.go:1312: race detected during execution of test
2022-09-09T14:39:13.8371679Z --- FAIL: TestClusterNode (372.86s)
2022-09-09T14:39:13.8374793Z === CONT  
2022-09-09T14:39:13.8375127Z     testing.go:1312: race detected during execution of test
2022-09-09T14:39:13.8375611Z FAIL
```

### PR DESCRIPTION
**Pull request by tssurya**
GetConfigDurationRecorder is called from two paths. 1) nodeTracker detects a switch or GR has been added for the node and does a full RequestFullSync which calls onServiceAdd 2) onServiceAdd is called from the service handler for adds.

If we don't lock the cdr variable we access it from two routines while one routine edits it; the other tries to read it for example. Let's lock this variable to prevent races.

```
2022-09-09T14:33:01.6982688Z WARNING: DATA RACE
2022-09-09T14:33:01.6982976Z Read at 0x000004402a78 by goroutine 1044:
2022-09-09T14:33:01.6983629Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.GetConfigDurationRecorder()
2022-09-09T14:33:01.6984387Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/metrics/master.go:847 +0x29b
2022-09-09T14:33:01.6985239Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*Controller).onServiceAdd()
2022-09-09T14:33:01.6986069Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/services_controller.go:366 +0x33f
2022-09-09T14:33:01.6986732Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*Controller).RequestFullSync()
2022-09-09T14:33:01.6988638Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/services_controller.go:351 +0x2b2
2022-09-09T14:33:01.6989314Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*Controller).RequestFullSync-fm()
2022-09-09T14:33:01.6989705Z       <autogenerated>:1 +0x39
2022-09-09T14:33:01.6990287Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*nodeTracker).updateNodeInfo()
2022-09-09T14:33:01.6991204Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/node_tracker.go:150 +0x67b
2022-09-09T14:33:01.6993403Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*nodeTracker).updateNode()
2022-09-09T14:33:01.6994200Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/node_tracker.go:201 +0x709
2022-09-09T14:33:01.6996051Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.newNodeTracker.func1()
2022-09-09T14:33:01.6996855Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/node_tracker.go:78 +0x55
2022-09-09T14:33:01.6998163Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
```

versus

```
2022-09-09T14:33:01.7016687Z Previous write at 0x000004402a78 by goroutine 1070:
2022-09-09T14:33:01.7017329Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.GetConfigDurationRecorder()
2022-09-09T14:33:01.7018197Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/metrics/master.go:848 +0x310
2022-09-09T14:33:01.7018912Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*Controller).onServiceAdd()
2022-09-09T14:33:01.7019866Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/services/services_controller.go:366 +0x33f
2022-09-09T14:33:01.7020529Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/services.(*Controller).onServiceAdd-fm()
2022-09-09T14:33:01.7020900Z       <autogenerated>:1 +0x4d
2022-09-09T14:33:01.7021431Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
2022-09-09T14:33:01.7022328Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:232 +0x74
2022-09-09T14:33:01.7022857Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
```

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
Closes #3154 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
Closes #3156

File: go-controller/pkg/metrics/master.go [hunk 1]
```diff
@@ -843,7 +843,12 @@ type ConfigDurationRecorder struct {
 // global variable is needed because this functionality is accessed in many functions
 var cdr *ConfigDurationRecorder
 
+// lock for accessing the cdr global variable
+var cdrMutex sync.RWMutex
```
Comment (martinkennelly) [inline go-controller/pkg/metrics/master.go:847]: why not a normal mutex, why RW?

Comment (tssurya) [reply go-controller/pkg/metrics/master.go:847]: didn't think too much, lol let me change to normal mutex since that is more perf efficient

**Comment by tssurya** [comment]
Opened https://github.com/ovn-org/ovn-kubernetes/issues/3157 for the existing failure in CI, doesn't seem related to this PR

**Review by trozet — APPROVED** [review]
