### PR TITLE
[CI] use fixed host network port range for ANP tests

### LINKED ISSUE #4348: CI flake: Admin net pol `TestNetworkPolicyV2Conformance` test attempting to use port already in-use
```
2024-05-09T17:45:20.1404158Z === RUN   TestNetworkPolicyV2Conformance
2024-05-09T17:45:20.1407058Z     network_policy_v2_test.go:31: Configuring environment for network policy V2 API conformance tests
2024-05-09T17:45:20.1421212Z     network_policy_v2_test.go:53: Starting the network policy V2 conformance test suite
2024-05-09T17:45:20.1422439Z     suite.go:125: Test Setup: Applying base manifests
2024-05-09T17:45:20.2616014Z     apply.go:124: Creating network-policy-conformance-gryffindor Namespace
2024-05-09T17:45:20.2686256Z     apply.go:124: Creating network-policy-conformance-slytherin Namespace
2024-05-09T17:45:20.2850881Z     apply.go:124: Creating network-policy-conformance-hufflepuff Namespace
2024-05-09T17:45:20.2958762Z     apply.go:124: Creating network-policy-conformance-ravenclaw Namespace
2024-05-09T17:45:20.3033351Z     apply.go:124: Creating network-policy-conformance-forbidden-forrest Namespace
2024-05-09T17:45:20.3185458Z     apply.go:124: Creating harry-potter StatefulSet
2024-05-09T17:45:20.3249033Z     apply.go:124: Creating draco-malfoy StatefulSet
2024-05-09T17:45:20.3312093Z     apply.go:124: Creating cedric-diggory StatefulSet
2024-05-09T17:45:20.3584068Z     apply.go:124: Creating luna-lovegood StatefulSet
2024-05-09T17:45:20.4050777Z     apply.go:124: Creating centaur StatefulSet
2024-05-09T17:45:20.4482467Z     suite.go:128: Test Setup: Ensuring Namespaces and Pods from base manifests are ready
2024-05-09T17:45:20.4551943Z     helper.go:123: StatefulSet replicas in namespace network-policy-conformance-gryffindor not rolled out yet. 0/2 replicas are available.
2024-05-09T17:45:21.4627860Z     helper.go:123: StatefulSet replicas in namespace network-policy-conformance-gryffindor not rolled out yet. 0/2 replicas are available.
....
....
2024-05-09T17:50:19.4577962Z     helper.go:123: StatefulSet replicas in namespace network-policy-conformance-forbidden-forrest not rolled out yet. 1/2 replicas are available.
2024-05-09T17:50:20.4499365Z     helper.go:120: Error retrieving StatefulSet harry-potter from namespace network-policy-conformance-gryffindor: client rate limiter Wait returned an error: context deadline exceeded
2024-05-09T17:50:20.4501830Z     helper.go:123: StatefulSet replicas in namespace network-policy-conformance-gryffindor not rolled out yet. 0/2 replicas are available.
2024-05-09T17:50:20.4502682Z     suite.go:143: 
2024-05-09T17:50:20.4503713Z         	Error Trace:	/home/runner/go/pkg/mod/sigs.k8s.io/network-policy-api@v0.1.5/conformance/utils/kubernetes/helper.go:130
2024-05-09T17:50:20.4505387Z         	            				/home/runner/go/pkg/mod/sigs.k8s.io/network-policy-api@v0.1.5/conformance/utils/suite/suite.go:143
2024-05-09T17:50:20.4507231Z         	            				/home/runner/go/pkg/mod/sigs.k8s.io/network-policy-api@v0.1.5/conformance/utils/suite/conformance_suite.go:132
2024-05-09T17:50:20.4509264Z         	            				/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/conformance/network_policy_v2_test.go:89
2024-05-09T17:50:20.4509992Z         	Error:      	Received unexpected error:
2024-05-09T17:50:20.4510860Z         	            	context deadline exceeded
2024-05-09T17:50:20.4511779Z         	Test:       	TestNetworkPolicyV2Conformance
2024-05-09T17:50:20.4514561Z         	Messages:   	error waiting for network-policy-conformance-gryffindor, network-policy-conformance-slytherin, network-policy-conformance-hufflepuff, network-policy-conformance-ravenclaw, network-policy-conformance-forbidden-forrest namespaces to be ready

```

I checked the logs for why one of the replicas pods isnt coming up and it complained about trying to bind to a port already in-use:

```shell
$cat 5.log 
2024-05-09T17:48:22.496335577Z stderr F I0509 17:48:22.496230       1 log.go:194] Started HTTP server on port 34358
2024-05-09T17:48:22.496458999Z stderr F I0509 17:48:22.496401       1 log.go:194] Started UDP server on port 172.18.0.3 34345
2024-05-09T17:48:22.4965566Z stderr F I0509 17:48:22.496512       1 log.go:194] listen tcp :34358: bind: address already in use
```

Seen in https://github.com/ovn-org/ovn-kubernetes/pull/4344 (https://github.com/ovn-org/ovn-kubernetes/actions/runs/9020680306/job/24814796912?pr=4344)

First time seeing it.

### PR DESCRIPTION
**Pull request by npinaeva**
## 📑 Description

https://github.com/kubernetes-sigs/network-policy-api/issues/341 (B)ANP conformance uses ports in range 34345-36366. 
This intersects with the default ephemeral port range > 32768.
This can cause an attempt to bind a port that is already used by another process and leads to test failure.

Fixes #4348

## ✅ Checks

- [ ] My code requires changes to the documentation
- [ ] if so, I have updated the documentation as required
- [ ] My code requires tests
- [ ] if so, I have added and/or updated the tests as required
- [ ] All the tests have passed in the CI 

## Summary by CodeRabbit

* **Chores**
  * Updated network policy API dependency to a newer version.

* **Refactor**
  * Streamlined conformance test configuration by introducing configurable host network port range settings for improved test flexibility and removing unused manifest references.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: test/conformance/network_policy_v2_test.go [hunk 1]
```diff
@@ -70,8 +66,12 @@ func TestNetworkPolicyV2Conformance(t *testing.T) {
 					suite.SupportAdminNetworkPolicyNamedPorts,
 					suite.SupportBaselineAdminNetworkPolicyNamedPorts,
 				),
-				BaseManifests: conformanceTestsBaseManifests,
```
Comment (tssurya) [inline test/conformance/network_policy_v2_test.go:73]: oh we don't need base manifests path anymore is it? did it get removed ? could you add a line on PR description or some info around this?

Comment (npinaeva) [reply test/conformance/network_policy_v2_test.go:73]: I think we never needed it, because it will then use manifests from the imported conformance version.
I am not sure why we had them before :/

Comment (tssurya) [reply test/conformance/network_policy_v2_test.go:73]: ah really? I was soo convinced this was a required thing somehow.. not sure if this is just in my head. oh well if its not required then let's get rid of dead code.

**Comment by npinaeva** [comment]
> hmm do we have another issue somewhere other than the port range feature we added?

good catch, that is an old comment from another fix, updated

**Review by tssurya — APPROVED** [review]
