### PR TITLE
Fix node ip migration encap

### LINKED ISSUE #3636: [Interconnect] [CI] Enable node-ip-migration tests in node-ip-migration lane
Node-IP migration lane fails with IC=true, these are disabled for now in https://github.com/ovn-org/ovn-kubernetes/pull/3366, we should fix the logic to work with IC and re-enable them.

/assign @trozet

### PR DESCRIPTION
**Pull request by trozet**
Fixes node ip migration with IC. Now on primary IP change, IC will call add local/remote zone node, which will properly update the encap for the chassis. Also re-enables node ip migration CI with IC. 1 additional commit to fix some things found along the way.

Closes #3636

### CODE REVIEW

**Comment by trozet** [comment]
Looks like there is some OVN bug here. @dceara will need your help on Monday. This case is with node ip migration. We have node ovn-worker and ovn-worker2. ovn-worker changes its ip to 172.18.255.254. A pod on ovn-worker (primary 10.244.0.3) tries to curl a pod on ovn-worker2 (secondary 10.244.1.6). The syn makes it to the secondary pod, the secondary pod replies with syn/ack. The syn/ack makes it to ovn-worker but then is not delivered to the pod:

tcpdump on ovn-worker for primary interface:
```
[root@ovn-worker ~]# tcpdump -i 54ced91366f798c port 8000 -nnev
dropped privs to tcpdump
tcpdump: listening on 54ced91366f798c, link-type EN10MB (Ethernet), snapshot length 262144 bytes
23:34:01.142066 0a:58:0a:f4:00:03 > 0a:58:0a:f4:00:01, ethertype IPv4 (0x0800), length 74: (tos 0x0, ttl 64, id 48716, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.3.58408 > 10.244.1.6.8000: Flags [S], cksum 0x171f (incorrect -> 0x6047), seq 1844583087, win 65280, options [mss 1360,sackOK,TS val 790173448 ecr 0,nop,wscale 7], length 0
23:34:12.195133 0a:58:0a:f4:00:03 > 0a:58:0a:f4:00:01, ethertype IPv4 (0x0800), length 74: (tos 0x0, ttl 64, id 10080, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.3.59202 > 10.244.1.6.8000: Flags [S], cksum 0x171f (incorrect -> 0x67f5), seq 4188166409, win 65280, options [mss 1360,sackOK,TS val 790184501 ecr 0,nop,wscale 7], length 0

```

syn/ack not seen, but looking at all interfaces:
```
[root@ovn-worker ~]# tcpdump -i any port 8000 -nnev
tcpdump: data link type LINUX_SLL2
dropped privs to tcpdump
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
23:34:43.785651 genev_sys_6081 P   ifindex 7 0a:58:a8:fe:00:03 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.1.6.8000 > 10.244.0.3.59202: Flags [S.], cksum 0x171f (incorrect -> 0xbe3c), seq 156746062, ack 4188166410, win 64704, options [mss 1360,sackOK,TS val 221369360 ecr 790184501,nop,wscale 7], length 0
23:34:45.350158 54ced91366f798c P   ifindex 8 0a:58:0a:f4:00:03 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 47290, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.3.55576 > 10.244.1.6.8000: Flags [S], cksum 0x171f (incorrect -> 0x4536), seq 3538693925, win 65280, options [mss 1360,sackOK,TS val 790217656 ecr 0,nop,wscale 7], length 0
23:34:45.350507 genev_sys_6081 Out ifindex 7 0a:58:a8:fe:00:02 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 63, id 47290, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.3.55576 > 10.244.1.6.8000: Flags [S], cksum 0x4536 (correct), seq 3538693925, win 65280, options [mss 1360,sackOK,TS val 790217656 ecr 0,nop,wscale 7], length 0
23:34:45.350964 genev_sys_6081 P   ifindex 7 0a:58:a8:fe:00:03 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.1.6.8000 > 10.244.0.3.55576: Flags [S.], cksum 0x171f (incorrect -> 0x3549), seq 1138943706, ack 3538693926, win 64704, options [mss 1360,sackOK,TS val 221370925 ecr 790217656,nop,wscale 7], length 0
23:34:46.410548 genev_sys_6081 P   ifindex 7 0a:58:a8:fe:00:03 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.1.6.8000 > 10.244.0.3.55576: Flags [S.], cksum 0x171f (incorrect -> 0x3125), seq 1138943706, ack 3538693926, win 64704, options [mss 1360,sackOK,TS val 221371985 ecr 790217656,nop,wscale 7], length 0
23:34:48.457558 genev_sys_6081 P   ifindex 7 0a:58:a8:fe:00:03 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.1.6.8000 > 10.244.0.3.55576: Flags [S.], cksum 0x171f (incorrect -> 0x2926), seq 1138943706, ack 3538693926, win 64704, options [mss 1360,sackOK,TS val 221374032 ecr 790217656,nop,wscale 7], length 0

```

Looking at datapath flows on ovn-worker, there is this giant recirculation loop:

```
recirc_id(0x49e),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-est-rel-rpl+inv+trk),ct_mark(0/0xf),eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01),eth_type(0x0800),ipv4(src=10.244.1.6,dst=10.244.0.2/255.255.255.254,proto=6,ttl=43,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct_clear,set(eth(src=0a:58:64:40:00:01,dst=0a:58:64:40:00:02)),set(ipv4(ttl=42)),check_pkt_len(size=1414,gt(sample(sample=100.0%,actions(meter(7),userspace(pid=4294967295,controller(reason=1,dont_send=0,continuation=0,recirc_id=1183,rule_cookie=0x8225376e,controller_id=0,max_len=65535))))),le(set(eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01)),set(ipv4(ttl=41)),check_pkt_len(size=1414,gt(ct(zone=1,nat),recirc(0x4a0)),le(ct(zone=1,nat),recirc(0x4a0)))))

recirc_id(0x4a0),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-rpl+trk),eth(),eth_type(0x0800),ipv4(src=10.244.1.6,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct(commit,nat(src=172.18.255.253)),recirc(0x4a1)


recirc_id(0x4a1),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-est-rel-rpl+inv+trk),ct_mark(0/0xf),eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01),eth_type(0x0800),ipv4(src=10.244.1.6,dst=10.244.0.2/255.255.255.254,proto=6,ttl=41,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct_clear,set(eth(src=0a:58:64:40:00:01,dst=0a:58:64:40:00:02)),set(ipv4(ttl=40)),check_pkt_len(size=1414,gt(sample(sample=100.0%,actions(meter(7),userspace(pid=4294967295,controller(reason=1,dont_send=0,continuation=0,recirc_id=1186,rule_cookie=0x8225376e,controller_id=0,max_len=65535))))),le(set(eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01)),set(ipv4(ttl=39)),check_pkt_len(size=1414,gt(ct(zone=1,nat),recirc(0x4a3)),le(ct(zone=1,nat),recirc(0x4a3)))))


recirc_id(0x4a3),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-rpl+trk),eth(),eth_type(0x0800),ipv4(src=10.244.1.6,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct(commit,nat(src=172.18.255.253)),recirc(0x4a4)


recirc_id(0x4a4),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-est-rel-rpl+inv+trk),ct_mark(0/0xf),eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01),eth_type(0x0800),ipv4(src=10.244.1.6,dst=10.244.0.2/255.255.255.254,proto=6,ttl=39,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct_clear,set(eth(src=0a:58:64:40:00:01,dst=0a:58:64:40:00:02)),set(ipv4(ttl=38)),check_pkt_len(size=1414,gt(sample(sample=100.0%,actions(meter(7),userspace(pid=4294967295,controller(reason=1,dont_send=0,continuation=0,recirc_id=1189,rule_cookie=0x8225376e,controller_id=0,max_len=65535))))),le(set(eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01)),set(ipv4(ttl=37)),check_pkt_len(size=1414,gt(ct(zone=1,nat),recirc(0x4a6)),le(ct(zone=1,nat),recirc(0x4a6)))))


recirc_id(0x4a6),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-rpl+trk),eth(),eth_type(0x0800),ipv4(src=10.244.1.6,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct(commit,nat(src=172.18.255.253)),recirc(0x4a7)


recirc_id(0x4a7),tunnel(tun_id=0xff0003,src=172.18.0.4,dst=172.18.255.254,geneve({}{}),flags(-df+csum+key)),in_port(5),ct_state(-new-est-rel-rpl+inv+trk),ct_mark(0/0xf),eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01),eth_type(0x0800),ipv4(src=10.244.1.6,dst=10.244.0.2/255.255.255.254,proto=6,ttl=37,frag=no), packets:445, bytes:32930, used:1.862s, flags:S., actions:ct_clear,set(eth(src=0a:58:64:40:00:01,dst=0a:58:64:40:00:02)),set(ipv4(ttl=36)),check_pkt_len(size=1414,gt(sample(sample=100.0%,actions(meter(7),userspace(pid=4294967295,controller(reason=1,dont_send=0,continuation=0,recirc_id=1192,rule_cookie=0x8225376e,controller_id=0,max_len=65535))))),le(set(eth(src=0a:58:64:40:00:02,dst=0a:58:64:40:00:01)),set(ipv4(ttl=35)),check_pkt_len(size=1414,gt(ct(zone=1,nat),recirc(0x4a9)),le(ct(zone=1,nat),recirc(0x4a9)))))

```

... it keeps going, but if you look at nat(src=172.18.255.253), this is an egress IP assigned to pod primary. The traffic should never be entering the gateway router...not sure what is going on here.

**Comment by trozet** [comment]
ah its because of the egress IP IC bug that @tssurya is fixing with https://github.com/ovn-org/ovn-kubernetes/pull/3825

[root@ovn-worker ~]# ovn-nbctl lr-route-list ovn_cluster_router
IPv4 Routes
Route Table <main>:
               100.64.0.2                100.64.0.2 dst-ip
               100.64.0.3               168.254.0.3 dst-ip
               100.64.0.4               168.254.0.4 dst-ip
               10.244.1.6                100.64.0.2 src-ip    <-------sending the reply packet to GR
            10.244.1.0/24               168.254.0.3 dst-ip
            10.244.2.0/24               168.254.0.4 dst-ip
            10.244.0.0/24                100.64.0.2 src-ip

I'll review 3825 now and then rebase this on top.

**Comment by trozet** [comment]
with #3825 applied all the tests pass. Will wait for that to merge then rebase this.

File: go-controller/pkg/libovsdb/libovsdb.go [hunk 1]
```diff
@@ -136,6 +136,10 @@ func NewSBClientWithConfig(cfg config.OvnAuthConfig, promRegistry prometheus.Reg
 	enableMetricsOption := client.WithMetricsRegistryNamespaceSubsystem(promRegistry,
 		"ovnkube", "master_libovsdb")
 
+	dbModel.SetIndexes(map[string][]model.ClientIndex{
+		sbdb.EncapTable: {{Columns: []model.ColumnKey{{Column: "chassis_name"}}}},
```
Comment (npinaeva) [inline go-controller/pkg/libovsdb/libovsdb.go:140]: one questions to that change: can there be existing leftover encaps for the same chassis_name but with different ips? If so, we may need to explicitly delete them before setting a new client index

File: go-controller/pkg/libovsdb/ops/model_client.go [hunk 2]
```diff
@@ -140,12 +140,14 @@ operationModel is a struct which uses reflection to determine and perform
...
-	// Model are used for mutations and updates as well. If this Model is
-	// looked up or created, it will have its UUID set after the operation.
+	// Model specifies the model to be created, or to look up in the cache.
+	// The values in the fields of the Model are used for mutations and updates
+	// as well. If this Model is looked up or created, it will have its UUID set
+	// after the operation.
 	Model interface{}
 	// ModelPredicate specifies a predicate to look up models in the cache.
+	// If Model is provided with non-zero index column values, ModelPredicate
+	// will be ignored.
```
Comment (jcaamano) [inline go-controller/pkg/libovsdb/ops/model_client.go:150]: :heart:

File: go-controller/pkg/libovsdb/libovsdb.go (hunk 1 above)
Comment (jluhrsen) [reply go-controller/pkg/libovsdb/libovsdb.go:140]: testing this PR locally I am seeing that old chassis encaps are cleaned up when the node ip is changed.

this is source and destination node encaps after changing source node IP 172.18..4 -> 172.18.255.254

source:

```
sh-5.2# ovn-sbctl list encap
_uuid               : 8e8adecc-b8f6-408a-9b8f-7bd2dffee37c
chassis_name        : "3dce988f-4195-45c0-9e6e-174d39abd704"
ip                  : "172.18.0.2"
options             : {csum="true"}
type                : geneve

_uuid               : 5a62ca06-9897-4a26-aa2e-e6327362f6d0
chassis_name        : "0a673b46-e8c7-4178-9b85-c11ca45f70e8"
ip                  : "172.18.255.254"
options             : {csum="true"}
type                : geneve

_uuid               : 3ccf1eab-5dc7-44b6-820d-a7279f176bf9
chassis_name        : "dda834ed-7ccd-4d3f-936f-bc912daefc06"
ip                  : "172.18.0.3"
options             : {csum="true"}
type                : geneve
```

destination:

```
sh-5.2# ovn-sbctl list encap
_uuid               : 409178bc-f6ad-497e-be0c-387e13044548
chassis_name        : "dda834ed-7ccd-4d3f-936f-bc912daefc06"
ip                  : "172.18.0.3"
options             : {csum="true"}
type                : geneve

_uuid               : f9b3430d-f238-47f0-9a4a-17284f3afce5
chassis_name        : "0a673b46-e8c7-4178-9b85-c11ca45f70e8"
ip                  : "172.18.255.254"
options             : {csum="true"}
type                : geneve

_uuid               : 2a3d4af6-8931-40ee-b435-e39dae7bebfd
chassis_name        : "3dce988f-4195-45c0-9e6e-174d39abd704"
ip                  : "172.18.0.2"
options             : {csum="true"}
type                : geneve
```

File: .github/workflows/test.yml [hunk 3]
```diff
@@ -395,6 +395,7 @@ jobs:
           - {"target": "control-plane",     "ha": "noHA", "gateway-mode": "shared", "ipfamily": "ipv4",      "disable-snat-multiple-gws": "noSnatGW", "second-bridge": "2br", "ic": "ic-single-node-zones"}
           - {"target": "multi-homing",      "ha": "noHA", "gateway-mode": "local",  "ipfamily": "ipv4",      "disable-snat-multiple-gws": "SnatGW",   "second-bridge": "1br", "ic": "ic-disabled"}
           - {"target": "node-ip-migration", "ha": "noHA", "gateway-mode": "shared", "ipfamily": "ipv6",      "disable-snat-multiple-gws": "SnatGW",   "second-bridge": "1br", "ic": "ic-disabled"}
+          - {"target": "node-ip-migration", "ha": "noHA", "gateway-mode": "shared", "ipfamily": "ipv4",      "disable-snat-multiple-gws": "SnatGW",   "second-bridge": "1br", "ic": "ic-single-node-zones"}
```
Comment (jluhrsen) [inline .github/workflows/test.yml:398]: do we want a v6 lane for this as well?

File: go-controller/pkg/libovsdb/libovsdb.go (hunk 1 above)
Comment (trozet) [reply go-controller/pkg/libovsdb/libovsdb.go:140]: also there cant be leftover encaps cause in 4.14 we go to IC so all new DBs are created. In the non-IC case there shouldn't be more than one encap per chassis, or odd things start happening with traffic flow.

File: .github/workflows/test.yml (hunk 3 above)
Comment (trozet) [reply .github/workflows/test.yml:398]: what did we have before? We have ipv6 covered in the non-ic lane

**Comment by trozet** [comment]
rebased now that https://github.com/ovn-org/ovn-kubernetes/pull/3825 is merged

**Review by jcaamano — APPROVED** [review]
