### PR TITLE
Fix EFW e2e flake: Don't pin NodePorts

### LINKED ISSUE #3970: flake: e2e egress firewall policy validation [It] Should validate the egress firewall allows inbound connection
looks like cleanup between test attempts didn't delete the service
https://github.com/ovn-org/ovn-kubernetes/actions/runs/6548450309/job/17784610721?pr=3895

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**
Splits out EFW e2e's into its own file
Also stops pinning nodePort svc in efw tests which is causing CI flakes like:
```
2023-12-23T19:37:51.4931054Z [38;5;243m------------------------------[0m
2023-12-23T19:37:51.4932481Z [0me2e egress firewall policy validation [0m[1mShould validate the egress firewall allows inbound connections[0m
2023-12-23T19:37:51.4934314Z [38;5;243m/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1377[0m
2023-12-23T19:37:51.4935888Z   [1mSTEP:[0m Creating a kubernetes client [38;5;243m@ 12/23/23 19:37:51.492[0m
2023-12-23T19:37:51.4937173Z   Dec 23 19:37:51.492: INFO: >>> kubeConfig: /home/runner/ovn.conf
2023-12-23T19:37:51.4939726Z   [1mSTEP:[0m Building a namespace api object, basename egress-firewall-policy [38;5;243m@ 12/23/23 19:37:51.493[0m
2023-12-23T19:37:51.4998932Z   Dec 23 19:37:51.499: INFO: Skipping waiting for service account
2023-12-23T19:37:51.5095912Z   [1mSTEP:[0m Creating the egress firewall pod [38;5;243m@ 12/23/23 19:37:51.509[0m
2023-12-23T19:37:51.6529146Z   W1223 19:37:51.651684   60892 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "e2e-egress-fw-pod-container" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "e2e-egress-fw-pod-container" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "e2e-egress-fw-pod-container" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "e2e-egress-fw-pod-container" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
2023-12-23T19:37:53.6631080Z   [1mSTEP:[0m Creating the nodePort service [38;5;243m@ 12/23/23 19:37:53.662[0m
2023-12-23T19:37:53.6681761Z   Dec 23 19:37:53.668: INFO: Unexpected error: 
2023-12-23T19:37:53.6682945Z       <*errors.StatusError | 0xc000c2a280>: 
2023-12-23T19:37:53.6693614Z       Service "nodeportsvc" is invalid: spec.ports[0].nodePort: Invalid value: 31234: provided port is already allocated
2023-12-23T19:37:53.6694774Z       {
2023-12-23T19:37:53.6695219Z           ErrStatus: 
2023-12-23T19:37:53.6695740Z               code: 422
2023-12-23T19:37:53.6696247Z               details:
2023-12-23T19:37:53.6696746Z                 causes:
2023-12-23T19:37:53.6697618Z                 - field: spec.ports[0].nodePort
2023-12-23T19:37:53.6699034Z                   message: 'Invalid value: 31234: provided port is already allocated'
2023-12-23T19:37:53.6700108Z                   reason: FieldValueInvalid
2023-12-23T19:37:53.6700796Z                 kind: Service
2023-12-23T19:37:53.6701416Z                 name: nodeportsvc
2023-12-23T19:37:53.6702816Z               message: 'Service "nodeportsvc" is invalid: spec.ports[0].nodePort: Invalid value:
2023-12-23T19:37:53.6704085Z                 31234: provided port is already allocated'
2023-12-23T19:37:53.6704833Z               metadata: {}
2023-12-23T19:37:53.6705433Z               reason: Invalid
2023-12-23T19:37:53.6706066Z               status: Failure,
2023-12-23T19:37:53.6706582Z       }
```
**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**
Use the helper libraries to create the nodePort svc without pinning ports.

Closes #3970

### CODE REVIEW

**Comment by tssurya** [comment]
@martinkennelly : PTAL this PR. It's better to leave nodeport allocation to be random and have no algorithm. It goes with how it behaves in actual world.

**Review by martinkennelly — APPROVED** [review]

File: test/e2e/egress_firewall.go [hunk 1]
```diff
@@ -532,9 +513,12 @@ spec:
 			framework.Failf("Failed to connect from pod to external container, before egress firewall is applied")
 		}
 		// external container -> nodePort svc should work
+		svc, err := f.ClientSet.CoreV1().Services(f.Namespace.Name).Get(context.TODO(), "service-for-pods", metav1.GetOptions{})
```
Comment (jcaamano) [inline test/e2e/egress_firewall.go:516]: nit: Use `serviceName` variable instead of `"service-for-pods"`

It is difficult to track that `createServiceForPodsWithLabel` uses that as a service name without that being defined as a constant somewhere or being passed in as a parameter.

File: test/e2e/egress_firewall.go [hunk 2]
```diff
@@ -491,26 +490,8 @@ spec:
...
-						Protocol:   v1.ProtocolTCP,
-						TargetPort: intstr.FromInt(efPodPort),
-					},
-				},
-				Selector: endpointsSelector,
-			},
-		}
-		_, err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Create(context.Background(), npSpec, metav1.CreateOptions{})
-		framework.ExpectNoError(err)
+		_, err = createServiceForPodsWithLabel(f, f.Namespace.Name, int32(servicePort), strconv.Itoa(efPodPort), "NodePort", endpointsSelector)
```
Comment (jcaamano) [inline test/e2e/egress_firewall.go:493]: I am confused because I see that this function receives a nodePort that is not being passed: https://github.com/tssurya/ovn-kubernetes/blob/af58536d749c2ad377e3e1a032375ffcee4dcb4c/test/e2e/e2e.go#L269-L270
```
func createServiceForPodsWithLabel(f *framework.Framework, namespace string, servicePort int32, targetPort string, nodePort int32, serviceType string, labels map[string]string) (string, error) {
```

File: test/e2e/egress_firewall.go (hunk 1 above)
Comment (tssurya) [reply test/e2e/egress_firewall.go:516]: ack yeah good point, let me fix this

Comment (tssurya) [reply test/e2e/egress_firewall.go:516]: done.

File: test/e2e/egress_firewall.go (hunk 2 above)
Comment (tssurya) [reply test/e2e/egress_firewall.go:493]: hmm where did you get this link from? I am also a bit confused.. perhaps the hash is wrong? can you double check. This PR https://github.com/ovn-org/ovn-kubernetes/pull/3481 is where I removed it.

**Comment by tssurya** [comment]
unrelated failure: https://github.com/ovn-org/ovn-kubernetes/issues/4104
this should be good to go @jcaamano PTAL.

File: test/e2e/egress_firewall.go (hunk 2 above)
Comment (jcaamano) [reply test/e2e/egress_firewall.go:493]: not sure anymore :P

**Review by jcaamano — APPROVED** [review]
